name: Deploy to Test

on:
  push:
    branches:
      - test

jobs:
  # Re use the Build Step
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    environment: test
    needs: build
    name: Deploy to Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set node from nvmrc
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: -c "sls config credentials --provider aws --key {{ secrets.TEST_AWS_ACCESS_KEY_ID }} --secret {{ secrets.TEST_AWS_SECRET_ACCESS_KEY }} && sls deploy --stage test --region eu-west-1 --force"
        entrypoint: /bin/sh
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: eu-west-1
